from __future__ import annotations

from typing import Any

class IRModule:
    def __init__(self, data: dict[str, Any] | None = ...) -> None: ...

def get_global_func(name: str) -> Any: ...

class Config: ...

class contrib:
    class stablehlo:
        @staticmethod
        def export(mod: Any, args: Any = ...) -> Any: ...
    class mlir:
        @staticmethod
        def emit_stablehlo(mod: Any) -> str: ...

class meta_schedule:
    class TuneContext: ...
    class TuningRecord: ...
    @staticmethod
    def tune_tir(
        mod: Any,
        target: Any,
        work_dir: str = ...,
        max_trials_global: int = ...,
        **kwargs: Any,
    ) -> list[Any]: ...


class tir:
    class Buffer: ...
    class PrimFunc: ...
    def max(self, a: Any, b: Any) -> Any: ...
    def cast(self, dtype: str, value: Any) -> Any: ...
    def float32(self, v: float) -> Any: ...
    def int32(self, v: int) -> Any: ...
    def grid(self, *args: int) -> Any: ...

    class axis:
        @staticmethod
        def remap(annotation: str, axes: list[Any]) -> list[Any]: ...
        @staticmethod
        def spatial(dim: int, i: int) -> Any: ...
        @staticmethod
        def reduce(dim: int, i: int) -> Any: ...
